"""Initial Migration

Revision ID: 52c6bb1ae35c
Revises: 4bb0e64406f2
Create Date: 2019-07-04 19:31:54.902883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c6bb1ae35c'
down_revision = '4bb0e64406f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('blogs', 'quote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('quote', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('blogs', 'content')
    # ### end Alembic commands ###
